# Generated by Django 5.0.3 on 2024-12-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='immage',
            field=models.ImageField(null=True, upload_to='bookimg/'),
        ),
    ]
