# Generated by Django 5.0.3 on 2024-12-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_immage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='immage',
            field=models.ImageField(null=True, upload_to='bookimg/'),
        ),
    ]
