# Generated by Django 5.0.3 on 2024-12-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinghistory',
            name='read',
        ),
    ]
